spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://db:5432/user_db # For Docker
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver